name: 'Destroy Frontend'

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

#Special permissions required for OIDC authentication.
permissions:
  id-token: write
  contents: read

#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    # environment:
    #   name: 'dev'
    
    steps:
    - name: Login to Azure
      id: LoginToAzure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    # Register Bypass CNAME check for custom domain deletion, so that custom domain can be deleted
    - name: Add Bypass CNAME check for custom domain deletion
      uses: azure/powershell@v2
      with:
        inlineScript: |
          Register-AzProviderFeature -ProviderNamespace Microsoft.Cdn -FeatureName BypassCnameCheckForCustomDomainDeletion
        azPSVersion: "latest"

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    # Terraform Destroy
    - name: Terraform Destroy
      id: tf-destroy
      run:  |
        terraform destroy -auto-approve
        if [ ${PIPESTATUS[0]} -ne 0 ]; then
          echo "Terraform Destroy failed."
          exit 1
        fi
      working-directory: ./terraform
    
    - name: Remove Bypass CNAME check for custom domain deletion
      uses: azure/powershell@v2
      with:
        inlineScript: |
          Unregister-AzProviderFeature -ProviderNamespace Microsoft.Cdn -FeatureName BypassCnameCheckForCustomDomainDeletion
        azPSVersion: "latest"