name: Deploy code to Website

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Login to Azure
        id: LoginToAzure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      
      - name: Deploy to Azure Static Website
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch -s website -d \$web --account-name <YourStorageAccountName>
